config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#root'

  resources :users_scores, only: [:create]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_scores_controller.rb
class UsersScoresController < ApplicationController
  def create
    @user = UsersScore.new(leaderboard_params)

    if @user.save
      render json: @user, status: :ok
    else
      render json: @user.errors.full_messages, status: :unprocessable_entity
    end
  end

  private
    def leaderboard_params
      params.require(:leaderboard).permit(:name, :score)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="icon" type="image/png" sizes="32x32" href="http://images.karenling.net/aa/flappy_pig/favicon.png">
  <link rel="icon" type="image/png" sizes="96x96" href="http://images.karenling.net/aa/flappy_pig/favicon.png">
  <link rel="icon" type="image/png" sizes="16x16" href="http://images.karenling.net/aa/flappy_pig/favicon.png">
  <title>Flappy Pig</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<footer>© <a href="http://www.karenling.net">Karen Ling</a></footer>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-4234175-13', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/static_pages/_leaderboard_form.html.erb
<form action="<%= users_scores_url %>" method="post" class="leaderboard">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="text" name="leaderboard[name]" id="leaderboard-name" placeholder="Click to add your name!">
  <input type="hidden" name="leaderboard[score]" id="leaderboard-score">

  <input type="Submit" class="submit-button" value="">
</form>


<script type="text/javascript">

  $('#leaderboard-name').click(function () {
    $('.submit-button').show();
  });


  $('.leaderboard').on('submit', function(event) {
    event.preventDefault();
    $('.submit-button').prop('disabled', true);
    var formData = $(event.currentTarget).serializeJSON();

    $.ajax({
      type: "POST",
      url: "/users_scores",
      dataType: "json",
      data: formData,
      success: function (response) {
        $('.errors').html("");
        $('.leaderboard').hide();
        handleSuccess(response);
      },
      error: function (response) {
        $('.errors').html(response.responseJSON[0]);
        $('.submit-button').prop("disabled", false);
      }
    })
  })

  function handleSuccess (response) {
    $('.submit-button').prop("disabled", false);

    $('.leaderboard-name').append($('<li>').html(response.name));


    var score;

    if (String(response.score).length === 3) {
      score = "0" + String(response.score);
    } else if (String(response.score).length === 2) {
      score = "00" + String(response.score);
    } else if (String(response.score).length === 1) {
      score = "000" + String(response.score);
    }

    $('.leaderboard-score').append($('<li>').html(score));
  };
</script>

app/views/static_pages/root.html.erb
<link href='https://fonts.googleapis.com/css?family=Monofett' rel='stylesheet' type='text/css'>

<div class="preload">
  <img src="http://images.karenling.net/aa/flappy_pig/landing.gif">
  <img src="http://images.karenling.net/aa/flappy_pig/bg_1.gif">
  <img src="http://images.karenling.net/aa/flappy_pig/bg_bar.gif">
  <img src="http://images.karenling.net/aa/flappy_pig/pig.png">
  <img src="http://images.karenling.net/aa/flappy_pig/pig_fly.png">
  <img src="http://images.karenling.net/aa/flappy_pig/pig_fly_down.png">
  <img src="http://images.karenling.net/aa/flappy_pig/pig_fall.png">
  <img src="http://images.karenling.net/aa/flappy_pig/pipe_top.png">
  <img src="http://images.karenling.net/aa/flappy_pig/pipe_bottom.png">
  <img src="http://images.karenling.net/aa/flappy_pig/score_board.png">
  <img src="http://images.karenling.net/aa/flappy_pig/leaderboard.gif">
  <img src="http://images.karenling.net/aa/flappy_pig/bg_gameover.gif">
  <img src="http://images.karenling.net/aa/flappy_pig/add_button_raised.gif">
  <img src="http://images.karenling.net/aa/flappy_pig/add_button_pressed.gif">
  <img src="http://images.karenling.net/aa/flappy_pig/button_restart_raised.gif">
  <img src="http://images.karenling.net/aa/flappy_pig/button_restart_pressed.gif">
  <img src="http://images.karenling.net/aa/flappy_pig/new_pig_variations2.gif">
  <div class="font-flappy">Preload</div>
  <div class="font-silk">Preload</div>
</div>

<div class="bg-image"></div>
<div class="iphone-image"></div>
<div class="container">
  <div class="errors"></div>
  <canvas class="flappy-view"></canvas>

  <%= render "leaderboard_form" %>

  <div class="leaderboard-container">
    <ul class="leaderboard-name">
      <% @users_scores.each do |user| %>
        <li><%= user.name %></li>
      <% end %>
    </ul>
    <ul class="leaderboard-score">
      <% @users_scores.each do |user| %>
        <li><%= (user.score.to_s).rjust(4, '0')  %></li>
      <% end %>
    </ul>
  </div>

  <div class="your-score"></div>
  <div class="restart-game"></div>
</div>

<script type="text/javascript">
    var canvasEl = document.getElementsByTagName("canvas")[0];
    canvasEl.height = 1024;
    canvasEl.width = 768;

    new FlappyPig.Game(
      canvasEl
    );
</script>